### ISSUE TITLE
Transfer Emails from Campaign Monitor

### ISSUE THREAD

**Issue by adzleach** [themarketingpod/nbs-2020-theme#14]
Transfer the following emails from campaign monitor to HubSpot for their inclusion in campaigns:

Can these please be built in the drag and drop editor so they can be edited directly by the nBs team.

### C&S Winback

1. C&S Winback Email 1 - http://npowerbusinesssolutions.npower.com/t/i-A3084631E33DE13D2540EF23F30FEDED
2. C&S Winback Email 2 - http://npowerbusinesssolutions.npower.com/t/i-E0DE1EAB69E07CC12540EF23F30FEDED
2. C&S Winback Email 3 - https://npowerbusinesssolutions.npower.com/t/i-e-mlhjlky-l-r/
3. C&S Winback Email 4 - http://npowerbusinesssolutions.npower.com/t/i-28218B4E5937207E2540EF23F30FEDED
4. C&S Winback Email 5 - https://npowerbusinesssolutions.npower.com/t/i-e-myuhrhk-l-r/
5. C&S Winback Email 6 - https://npowerbusinesssolutions.npower.com/t/i-e-myueid-l-r/

Can you let Roz know when complete so she can tell Kavshi?

**Comment by Coleus99** [comment]
setup on Hubspot and emailed Roz to inform its complete
